english: "en"
vietnam: "vi"
maximum_length_name: 50
maximum_length_email: 255
minimum_length_password: 6
size_gravatar: 80
remember_me : "1"
per_page: 10
time_reset: 2
micropost_maximum_length_content: 140
per_page_micropost: 5
per_page_feed: 5
per_page_user: 10
picture_size: 1
picture_x: 400
picture_y: 400
error_image_size: "Image is than 1MB"
gravatar_size_html: 50
accept_picture: "image/jpeg,image/gif,image/png"
per_page_follow: 10
name_length_maximum: 150
name_length_minimum: 3
content_text_max_length: 500
content_text_min_length: 100
picture: "image/jpeg, image/gif, image/png,
  image/jpg, image/svg"
parger: 5
size_picture: 80
